### ISSUE TITLE
instead of 'My Profile' tab, it would be clearer for user to say their name or their email 

### ISSUE THREAD

**Issue by TedEwanchyna** [MeteorMTL/magnet#20] opened 2015-07-05 17:12 UTC
for example Ted's Profile tab instead of 'My Profile'
For some reason, probably because I have more than one account, it is useful to to see my name at the top of the page and customising the 'My Profile' tab is an obvious place to do this.

**Comment by pcuci** [comment] 2015-07-05 17:16
Duplicate of #19

**Closed as completed** 2015-08-01 23:37 UTC
Labels: duplicate
